server:
  address: localhost
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    hostname: localhost
    preferIpAddress: false

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

reactive:
  feign:
    loadbalancer:
      enabled: false
    client:
      config:
        catalog-service:
          options:
            readTimeoutMillis: 2000
            connectTimeoutMillis: 1000
        inventory-service:
          options:
            readTimeoutMillis: 2000
            connectTimeoutMillis: 1000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      CatalogApiClient_searchProductsBySku_String:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10000
      CatalogApiClient_getProductById_String:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10000
      InventoryApiClient_getInventoryForProducts_List:
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
